import {
  FileAddOutlined,
  FileTextOutlined,
  FolderOpenOutlined,
  SettingOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  FallOutlined,
  RiseOutlined,
  BellOutlined,
  SwapOutlined,
  ExclamationCircleOutlined,
  CalendarOutlined,
  UnorderedListOutlined,
  RetweetOutlined,
  FileSearchOutlined,
  SwapRightOutlined,
  SafetyOutlined,
  TeamOutlined,
  ForkOutlined,
  BankOutlined,
  IdcardOutlined,
  AppstoreOutlined,
  ProjectOutlined,
  DollarOutlined,
  ApartmentOutlined,
  SolutionOutlined,
} from '@ant-design/icons';

/**
 * Mapeo id de ítem de menú → ícono.
 * Centralizado para mantener consistencia.
 */
export const menuIconMap: Record<string, React.ReactNode> = {
  'personal-actions': <FileAddOutlined />,
  'payroll-params': <FileTextOutlined />,
  'payroll-management': <FolderOpenOutlined />,
  configuration: <SettingOutlined />,
  'entradas-personal': <UserAddOutlined />,
  'salidas-personal': <UserDeleteOutlined />,
  deducciones: <FallOutlined />,
  compensaciones: <RiseOutlined />,
  incapacidades: <BellOutlined />,
  'licencias-permisos': <SwapOutlined />,
  ausencias: <ExclamationCircleOutlined />,
  'calendario-nomina': <CalendarOutlined />,
  'articulos-nomina': <UnorderedListOutlined />,
  'movimientos-nomina': <RetweetOutlined />,
  planillas: <FileSearchOutlined />,
  'traslado-interempresas': <SwapRightOutlined />,
  permissions: <SafetyOutlined />,
  roles: <SafetyOutlined />,
  'users-access': <TeamOutlined />,
  'reglas-distribucion': <ForkOutlined />,
  empresas: <BankOutlined />,
  empleados: <IdcardOutlined />,
  clases: <AppstoreOutlined />,
  proyectos: <ProjectOutlined />,
  'cuentas-contables': <DollarOutlined />,
  departamentos: <ApartmentOutlined />,
  puestos: <SolutionOutlined />,
};
