export const PERSONAL_ACTION_INVALIDATED_BY = {
  SYSTEM: 'SYSTEM',
  USER: 'USER',
} as const;

export type PersonalActionInvalidatedByType =
  (typeof PERSONAL_ACTION_INVALIDATED_BY)[keyof typeof PERSONAL_ACTION_INVALIDATED_BY];

export const PERSONAL_ACTION_INVALIDATION_REASON = {
  TERMINATION_EFFECTIVE: 'TERMINATION_EFFECTIVE',
  COMPANY_MISMATCH: 'COMPANY_MISMATCH',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  MANUAL_INVALIDATION: 'MANUAL_INVALIDATION',
} as const;

export type PersonalActionInvalidationReasonCode =
  (typeof PERSONAL_ACTION_INVALIDATION_REASON)[keyof typeof PERSONAL_ACTION_INVALIDATION_REASON];

